"""Standalone Robometer eval-server launcher - install, patch, and run anywhere.

The one script that turns a machine with an NVIDIA GPU into a reward-scoring
server: it installs robometer at a pinned commit (their repo has no license,
so we can't vendor the code - we fetch and patch it on the user's machine),
downloads the Robometer-4B checkpoint at a pinned revision, applies two dtype
fixes the published checkpoint needs (see apply_patches), and starts their
FastAPI eval server.

Local:   python run_robometer_server.py            # serves on 0.0.0.0:8001
Cloud:   modal_eval_server.py wraps this same file - install/download at image
         build time (--install-only), patch + launch at container start.

Point ROBOMETER_URL at the running server and run the demo generated by
`daft-physical-ai rewards` (which scaffolds this file).
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

ROBOMETER_COMMIT = "5b815254bf31ee1bea3753c3a2da9f9033736d9a"  # main, 2026-07-01
MODEL_ID = "robometer/Robometer-4B"
HF_REVISION = "beef63bc914c5c189329d49c6d712d96d632aa34"

DEFAULT_ROOT = Path(os.environ.get("ROBOMETER_ROOT", Path.home() / ".robometer" / "robometer"))
DEFAULT_MODEL_DIR = Path(os.environ.get("ROBOMETER_MODEL_DIR", Path.home() / ".robometer" / "model"))


def ensure_install(root: Path) -> None:
    """Clone robometer at the pinned commit and pip-install it (idempotent)."""
    if not (root / "setup.py").exists():
        root.parent.mkdir(parents=True, exist_ok=True)
        subprocess.run(["git", "clone", "https://github.com/robometer/robometer.git", str(root)], check=True)
        subprocess.run(["git", "-C", str(root), "checkout", ROBOMETER_COMMIT], check=True)
    subprocess.run([sys.executable, "-m", "pip", "install", "-e", str(root)], check=True)
    # robometer declares transformers>=4.57 with no ceiling; newer releases
    # changed the Qwen3-VL contract (mm_token_type_ids required), which their
    # forward path predates. Pin to the era they developed against.
    subprocess.run([sys.executable, "-m", "pip", "install", "transformers==4.57.1"], check=True)


def ensure_model(model_dir: Path) -> None:
    """Download the checkpoint at the pinned revision as a local dir (idempotent),
    plus the base tokenizer/processor files the checkpoint repo doesn't carry."""
    from huggingface_hub import snapshot_download

    snapshot_download(MODEL_ID, revision=HF_REVISION, local_dir=str(model_dir))
    snapshot_download(
        "Qwen/Qwen3-VL-4B-Instruct",
        ignore_patterns=["*.safetensors", "*.bin", "*.pth"],
    )


def apply_patches(root: Path) -> None:
    """Dtype fixes the published checkpoint needs (robometer commit 5b81525;
    upstream issue: daft-physical-ai#31).

    The checkpoint is mixed-dtype (vision-tower norm weights fp32, rest bf16)
    and the eval server neither unifies the model dtype nor casts float inputs,
    so layer_norm crashes. Cast the model uniformly to bf16 on GPU (what vLLM
    does with the config's `bfloat16`) and float inputs to match. Idempotent.
    """
    server_py = root / "robometer" / "evals" / "eval_server.py"
    src = server_py.read_text()
    src = src.replace(
        "model = model.to(device)",
        "model = model.to(device, torch.bfloat16)",
    )
    src = src.replace(
        "[key] = value.to(device)",
        "[key] = (value.to(device, torch.bfloat16) "
        "if value.is_floating_point() else value.to(device))",
    )
    server_py.write_text(src)


def launch(root: Path, model_dir: Path, host: str, port: int) -> subprocess.Popen:
    """Start the patched eval server; returns the process."""
    return subprocess.Popen(
        [
            sys.executable,
            "robometer/evals/eval_server.py",
            f"model_path={model_dir}",
            "num_gpus=1",
            "max_workers=1",
            f"server_url={host}",
            f"server_port={port}",
        ],
        cwd=str(root),
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", type=Path, default=DEFAULT_ROOT, help="where the robometer repo lives")
    parser.add_argument("--model-dir", type=Path, default=DEFAULT_MODEL_DIR, help="where the checkpoint lives")
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--port", type=int, default=8001)
    parser.add_argument(
        "--install-only", action="store_true", help="install + download model, don't serve (for image builds)"
    )
    args = parser.parse_args()

    ensure_install(args.root)
    ensure_model(args.model_dir)
    if args.install_only:
        return
    apply_patches(args.root)
    proc = launch(args.root, args.model_dir, args.host, args.port)
    try:
        sys.exit(proc.wait())
    except KeyboardInterrupt:
        proc.terminate()
        proc.wait()


if __name__ == "__main__":
    main()
