"""Hand tracking demo - MediaPipe (local runtime)

Generated by `daft-physical-ai`. Reads a LeRobot dataset, runs hand tracking as a
Daft UDF, and shows the annotated frames. Runs on this machine - WiLoR needs a
local CUDA GPU; MediaPipe runs on CPU.
"""
from __future__ import annotations

from daft.datasets import lerobot

from daft_physical_ai import track_hands

DATASET = "pepijn223/egodex-test"
IMAGE_COLUMN = "observation.image"
LIMIT = 12

df = lerobot.read(DATASET, load_video_frames=IMAGE_COLUMN).limit(LIMIT)

df = df.with_column("hands", track_hands(df[IMAGE_COLUMN], method="mediapipe"))

df.select("episode_index", "frame_index", "hands").show()
